insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (1, 'Allissa', 'Phelips', 'aphelips0@archive.org', 'Cisgender Male', '49.23.91.194', '#32c8da');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (2, 'Monty', 'Episcopio', 'mepiscopio1@google.nl', 'FTM', '172.193.219.190', '#14449c');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (3, 'Ariana', 'Ockendon', 'aockendon2@51.la', 'Neither', '185.63.140.242', '#3dcac1');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (4, 'Reinold', 'Tribe', 'rtribe3@prnewswire.com', 'Gender Variant', '17.65.78.237', '#883b88');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (5, 'Lauralee', 'McAmish', 'lmcamish4@unicef.org', 'Transgender Man', '253.254.73.21', '#1e56fe');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (6, 'Finn', 'Masse', 'fmasse5@berkeley.edu', 'Transsexual Male', '233.107.161.41', '#5a36e0');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (7, 'Brady', 'Buey', 'bbuey6@chronoengine.com', 'Gender Questioning', '44.89.212.196', '#4d4795');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (8, 'Laurie', 'MacKeeg', 'lmackeeg7@columbia.edu', 'Non-binary', '76.204.251.8', '#aa0361');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (9, 'Francoise', 'Stollenwerck', 'fstollenwerck8@cafepress.com', 'Androgynous', '108.175.33.0', '#1c6670');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (10, 'Amanda', 'Stuehmeier', 'astuehmeier9@phpbb.com', 'Male to Female', '81.111.214.134', '#25760a');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (11, 'Aloysia', 'Frend', 'afrenda@hao123.com', 'Non-binary', '66.95.42.52', '#398d97');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (12, 'Licha', 'Arkow', 'larkowb@ox.ac.uk', 'Androgynous', '210.234.196.73', '#e3ac91');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (13, 'Lucio', 'Margett', 'lmargettc@squidoo.com', 'Transgender Female', '88.198.253.10', '#14f85e');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (14, 'Sargent', 'Widocks', 'swidocksd@list-manage.com', 'Gender Fluid', '38.118.57.173', '#194c7c');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (15, 'Charmaine', 'Boldry', 'cboldrye@blogspot.com', 'Transgender', '112.162.8.180', '#baded9');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (16, 'Andrei', 'Badder', 'abadderf@tmall.com', 'Trans Female', '27.135.130.135', '#e11865');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (17, 'Penni', 'Dargan', 'pdargang@ning.com', 'Cis Woman', '101.10.26.16', '#a0700a');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (18, 'Carey', 'Setchell', 'csetchellh@weibo.com', 'Transgender Woman', '62.33.247.139', '#101d6b');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (19, 'Cesaro', 'McReedy', 'cmcreedyi@oaic.gov.au', 'Cisgender Female', '53.216.57.245', '#74da32');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (20, 'Keane', 'Belasco', 'kbelascoj@sohu.com', 'Non-binary', '236.109.198.232', '#08f27d');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (21, 'Pier', 'Balaison', 'pbalaisonk@unesco.org', 'Transsexual Female', '84.198.53.247', '#b92460');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (22, 'Ricki', 'Moine', 'rmoinel@infoseek.co.jp', 'MTF', '146.136.255.113', '#7c3dc5');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (23, 'Cindee', 'Dunnett', 'cdunnettm@ocn.ne.jp', 'Transsexual', '221.233.100.131', '#db9de7');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (24, 'Devonna', 'Tothe', 'dtothen@twitpic.com', 'Transsexual Man', '33.40.70.191', '#3cdd0e');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (25, 'Bridget', 'Perrett', 'bperretto@hao123.com', 'Cisgender Woman', '119.255.37.143', '#834d01');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (26, 'Maiga', 'Cradock', 'mcradockp@apple.com', 'Trans Woman', '97.183.93.84', '#c80f60');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (27, 'Doug', 'Sirkett', 'dsirkettq@vimeo.com', 'MTF', '64.90.171.190', '#2d4e81');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (28, 'Brady', 'Rogez', 'brogezr@macromedia.com', 'Transgender Male', '199.249.243.34', '#41c82a');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (29, 'Jacky', 'Jancic', 'jjancics@linkedin.com', 'Transgender', '198.179.225.178', '#34331d');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (30, 'Romain', 'Itzkovitch', 'ritzkovitcht@wordpress.org', 'Trans Female', '159.191.63.127', '#7e9dfb');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (31, 'Pepita', 'Tremmil', 'ptremmilu@ustream.tv', 'Transgender Man', '57.6.3.70', '#c9e983');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (32, 'Dorrie', 'De Pietri', 'ddepietriv@theatlantic.com', 'Cis Man', '108.163.136.74', '#9d9d3f');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (33, 'Yance', 'Rycroft', 'yrycroftw@arstechnica.com', 'Trans Man', '243.244.113.192', '#666a12');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (34, 'Pia', 'Balharrie', 'pbalharriex@shareasale.com', 'Pangender', '134.131.36.174', '#f1ad34');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (35, 'Angele', 'Po', 'apoy@google.ru', 'Trans Female', '31.152.73.239', '#a349e2');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (36, 'Zita', 'Dunks', 'zdunksz@stumbleupon.com', 'Transgender Man', '39.209.85.222', '#a4f3da');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (37, 'Linus', 'Rossbrook', 'lrossbrook10@geocities.com', 'Transgender', '181.57.30.85', '#bfae46');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (38, 'Udell', 'Venables', 'uvenables11@vimeo.com', 'Female to Male', '152.87.170.197', '#9b2a81');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (39, 'Mathias', 'Freschi', 'mfreschi12@printfriendly.com', 'Neutrois', '46.53.10.94', '#5097c6');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (40, 'Marji', 'Keerl', 'mkeerl13@globo.com', 'Cis Male', '185.186.206.116', '#c0ee74');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (41, 'Elberta', 'Padbery', 'epadbery14@pen.io', 'Trans', '0.201.248.17', '#973e58');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (42, 'Mikol', 'Glasson', 'mglasson15@mapy.cz', 'Androgyne', '255.59.52.195', '#53cb9b');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (43, 'Regen', 'Palluschek', 'rpalluschek16@blog.com', 'Trans Man', '70.67.178.118', '#38eee0');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (44, 'Boote', 'Klima', 'bklima17@stanford.edu', 'Transsexual Woman', '113.169.93.51', '#b301a2');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (45, 'Netti', 'Keeble', 'nkeeble18@ihg.com', 'Cis', '189.231.154.20', '#06f795');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (46, 'Adrianne', 'Osselton', 'aosselton19@jalbum.net', 'Transmasculine', '18.153.170.134', '#880357');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (47, 'Verile', 'Loxton', 'vloxton1a@about.me', 'Cisgender Woman', '114.202.46.146', '#1203de');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (48, 'Kiri', 'Southworth', 'ksouthworth1b@hhs.gov', 'Cis Woman', '70.88.124.240', '#14dca4');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (49, 'Luciana', 'Hubber', 'lhubber1c@imgur.com', 'Pangender', '6.20.91.218', '#940fa9');
insert into pracownicy (id, first_name, last_name, email, gender, ip_address, color) values (50, 'Rodger', 'Moulton', 'rmoulton1d@deliciousdays.com', 'Cis Female', '63.42.214.137', '#bacf9f');
